### PR TITLE
Handle parens for it, describe, and friends

### LINKED ISSUE #7: Doesn't recognize tests using paren call syntax
`testrbl` finds

```
it 'tests something' do
```

just fine, but fails to see

```
it('tests something') do
```

### PR DESCRIPTION
**Pull request by srvance**
Fixes #7 

* Adds tests that fail before the change and pass after.
* Adds to the patterns to allow parens with potentially no whitespace around the open paren or before the close paren.
* Adjusts third pattern to maintain positional correspondence of capture groups.
* Corrects a typo.

Note that one test fails on master before and after this change.

### CODE REVIEW

File: lib/testrbl.rb [hunk 1]
```diff
@@ -2,9 +2,9 @@
 
 module Testrbl
   PATTERNS = [
-    /^(\s+)(should|test|it)\s+['"](.*)['"]\s+do\s*(?:#.*)?$/,
-    /^(\s+)(context|describe)\s+['"]?(.*?)['"]?\s+do\s*(?:#.*)?$/,
-    /^(\s+)def\s+(test_)([a-z_\d]+)\s*(?:#.*)?$/
+    /^(\s+)(should|test|it)(\s+|\s*\(\s*)['"](.*)['"](\s*\))?\s+do\s*(?:#.*)?$/,
```
Comment (grosser) [inline lib/testrbl.rb:5]: I was thinking:
```suggestion
    /^(\s+)(should|test|it)\s+['"(](.*)['")]\s+do\s*(?:#.*)?$/,
```
since  nobody does `it ( "foo" )` anyway 🤷

Comment (srvance) [reply lib/testrbl.rb:5]: The tests I found this on do `it('foo') do`. Some even do `it('foo') { code }`, which this doesn't yet address.

Some key differences with your suggestion are

1. The paren isn't an alternative for the quotes, so a multiplier would have to be added
1. We would need to change the whitespace to allow zero whitespace
